### ISSUE TITLE
how can I deploy my pages to multiple repos?

### ISSUE THREAD

**Issue by ewnit** [nielsenramon/chalk#11]
I want to customize my pages to multiple repos like this

```
deploy:
  type: git
  repo:
    github: git@github.com:xxx/xxx.github.io.git,master
    coding: git@git.coding.net:xxx/xxx,coding-pages
    gitcafe: git@gitcafe.com:xxx/xxx.git,gitcafe-pages
```

for some reasons(Chinese web user) sometimes I even can not access github pages
