### ISSUE TITLE
Encountering issues when deploying _site 

### ISSUE THREAD

**Issue by christiantype** [nielsenramon/chalk#13]
I've used `jekyll build` to generate my `_site` which I've uploaded to my live domain which can be viewed here:  http://christiansolorzano.com/demo/

Can anybody let me know what is happening? Links are not working and neither are the stylesheets. Here is my repositirory: https://github.com/christiantype/jekyll-bourbon-test

Thanks

**Comment by nielsenramon** [comment]
@christiantype Have you tried setting the baseurl to demo? As you aren't using the root domain.

**Comment by christiantype** [comment]
Great! That seemed to fix things :-)  http://christiansolorzano.com/demo/ 

Some links are broke now. Below is what is in my _config.yml. Should /demo/ be included elsewhere besides the baseurl?

```
# Mandatory settings

baseurl: /demo/
name: Chalk
paginate: 25
paginate_path: "/posts/page/:num/"
url: # add site url http://example.com/
blog_theme: light # Or use dark

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble link
  facebook: # Add your Facebook link
  github: # Add your GitHub link
  linkedin: # Add your LinkedIn link
  twitter: # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - bourbon
  - neat
permalink: posts/:slug

```
