### ISSUE TITLE
Navigating to pages produces 404

### ISSUE THREAD

**Issue by nikolalukovic** [nielsenramon/chalk#14]
Hi, 
I'm using nginx to host a blog with this theme and everything works except navigating to pages.
You can check out the website [here](https://nikolalukovic.com).
What happens is when you try to navigate to a [page](https://nikolalukovic.com/posts/introducing-chalk), 404 pops up, but if you add .html at the end of the page than everything works correctly.

If i use --serve handle from jekyll to debug than it also works.

Here is my _config.yml:

```
# Mandatory settings

baseurl:
name: Nikola Lukovic
paginate: 25
paginate_path: "/posts/page/:num/"
url: https://nikolalukovic.com # add site url http://example.com/
blog_theme: light # Or use dark

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
rss_enabled: false # Change to false if not
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  github: nikolalukovic
  linkedin: # Add your LinkedIn handle
  twitter: lichtnik
  email: nikola.lukovic@live.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: posts/:slug
```
