### ISSUE TITLE
Use svg icons instead of ionicons font

### ISSUE THREAD

**Issue by migueldemoura** [nielsenramon/chalk#59]
Pretty self-explanatory.
We not only use a tiny subset of that font, but there are advantages to using svg over font for icons.

Some further insight into this [here](https://css-tricks.com/icon-fonts-vs-svg/).

Ionicons in svg: https://github.com/driftyco/ionicons/tree/master/src

**Comment by migueldemoura** [comment]
@nielsenramon, do you want me to use css or import the .svg directly?

```css
.icon-github {
     background-image: url('icons/github.svg');
}
```
```html
<img class="icon icon-github">
```

or
```html
<img class="icon" src="icons/github.svg">
```
